### ISSUE TITLE
Kanban board setup: Final Capstone Project

### ISSUE THREAD

**Issue by Kandy-Peter** [Kandy-Peter/car-booking-back-end#19]
## Project details:
 Total members: 

1. Kandy Peter
2. Hammas Saleem
3. Farouq Daif

Here is our kanban [link](https://github.com/Kandy-Peter/car-booking-back-end/projects/1)
![kanban](https://user-images.githubusercontent.com/93039359/174112295-f5748b6e-0454-49c2-8118-18288731158e.png)

**Comment by MuriloRoque** [comment]
Hi @Kandy-Peter, @farouqdaif1, @HAMMAS-SALEEM,

Good job so far!
There are some issues that you still need to work on but you are almost there!

## Suggested changes

- [ ] Please put a screenshot of your Kanban board in this issue's description, just like it's mentioned in [the requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md).

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by MuriloRoque** [comment]
Hi @Kandy-Peter, @farouqdaif1, @HAMMAS-SALEEM,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
